name: mongo_basic_utils
description: basic utils package for mongo_dart, without json annotation to allow conduit framework to build without relying on dart:mirrors.
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  http:
  logging: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
